image: node:latest
cache:
  paths:
    - node_modules/

before_script:
  - npm config set '//gitlab.com/api/v4/projects/18231362/packages/npm/:_authToken' "${NPM_TOKEN}"
  - npm config set '//gitlab.com/api/v4/packages/npm/:_authToken' "${NPM_TOKEN}"

build:
  stage: build
  script:
    - npm ci
    - npm run build:ci
  artifacts:
    paths:
      - dist
      - node_modules

unit_test:
  stage: build
  script:
    - npm install
    - npm test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

publish:
  stage: deploy
  only:
    refs:
      - master
      - tmo/master
  dependencies:
    - build # Pulls in the artifacts from the build stage
  script:
    - npm publish

publish_docs:
  stage: deploy
  trigger:
    project: tmobile/iot-mobile/website
    branch: tmo/master
