language: node_js
node_js:
- '14'
cache:
  directories:
  - node_modules
install:
- npm install
jobs:
  include:
  - stage: build
    if: "(type IN (pull_request))"
    script: npm run test && npm run build
  - stage: deploy
    if: tag IS present
    script: npm run test && npm run build
    deploy:
      provider: npm
      email: OpenDevWG@t-mobile.com
      api_key:
        secure: jgT0Vj9M6f9UqAkUMQLFyjjQfV2McZWTsSnWzJmFs7E9xCMnUoY10wwthqPccryOOB1Cm8E4WdqMqmzScC2WEIMKsJS4uLVacUyXcxMRcXzlQT83SlT7b1Ih1IyopHCvQ5N49GSUujAUlWCBJZbUmWJeOx4ok7sQ6yq7Bds8JxiA9mjQMoYM1FkdXRR5DE1yEh3jy+4YEeEi+NX2pju7U633B8ZMn5MPTGIjvb8oYEtl0xEwg3qbHXQkyhZEEUX0im30K+RMhE2oCu98/F5dedKSqpiKQJwxcJhS62C047R2/JxkjMeylal8o7vG1br3a97MP1klqAS8YXB7Bev1o9jXFbc66KAZA2FQJsBq3FOyVxspRsNj+boc+5KsUUHBaw3Rx1MrRlyGvyZ2fyoAlFiQX5e40QlQJwtEPFgYdLyzRFklZLW20bZ4e8mJ/PrLZOdD8AqNN1Gzn4aCwDP5bGpqqNlECDeYLHkoormMMwUNajj6Zbn5ZUssANq9zuVLGrut0Z9bAvJAiZbPsj+NMp5TZ7wdfMs21Or/2VKg++Qd1rGhGve9PGI6dHKwN/8RjsWOZeyQu6Kp6wqBXIozxbbwJwdQkGf071ciEvWEUo8KppPlibdJ7jCX7MOYow/Ec5Qz+ChxDC/gLa5pz/QBSyBKf7kIkRExr1LlkRlhLfY=
      on:
        tags: true
      skip_cleanup: true
