language: node_js
node_js:
- '14'
cache:
  directories:
  - node_modules
install:
- npm install
jobs:
  include:
  - stage: build
    if: "(type IN (pull_request))"
    script: npm run test && npm run build
deploy:
  provider: npm
  email: OpenDevWG@t-mobile.com
  api_key:
    secure: o1Ajlq/lG5KeuS3REFum9MbJzJr1MscDknPMg/8owjzZymAseAzhAmPET5KUusPjBfqSHFH6YMMzTJNWtxLxzOqUYGbrlLZn1YREJgWygRQCyN69eMkPh3I7/imlLeG8taA/dagTTUSRh5IW3XmcFMEDqYF+pKvqDPgh4fIoKfmvBKLnZ+aeNAbnI4YIzh8ynAgqLQFrqhPzLn1YPMVsJgc6ZWsqryGtbWRMjXc8ic3VplnoWnBlrCLH/j0X6a/xSt34feBuH1fNfGFKIumhvbCG6yMz6lp4ns50U0SY5OkhZB9npXul0zws+GhNIpH1sH/iDdXDkBs65DAYRlDnlY88RHQ4o1/pE5F4GDtWkcWGw2r1A8b1fV5mgrzeu5W8OiHynVjtC/qBgQHHj7sGfA6J4sJ6CrOq4IMkIkTbUCay/xYhFvGfNENGdh7XXuUisQfv9YoeprHG2jUf22TaSGMxUNlevMJR7uOTYs0iNJVcHBwJIpq+8lsrcgXEj7cPPCCN0pzfToWawm6D0PQjFvko/VpBJ5rwzlOsy+8LrOGJyjmOfP7UOmH+2Jy4Ex9iwkNe4ortU4nLRZ13wcmS5ftfCqpQbWCRaEhqUmU/RZb6MtRdGpLXlf4kQ03I4arfdng4RJmCg3/mzUhZw9FxQa8ekHUdXY7OQi65OB9/C6Y=
  on:
    tags: true
    repo: tmobile/node-red-contrib-array-iterator
    branch: master
    tag: stable
  skip_cleanup: 'true'
