language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules
install:
  - npm install
jobs:
  include:
    - stage: build
      if: (type IN (pull_request))
      script: npm run test && npm run build
